name: Debugging with SSH
on:
  push:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            TARGET: x86_64-unknown-linux-musl
            COMPILER: gcc
            LINKER: gcc
    steps:
      - uses: actions/checkout@v2
      - name: Create Build Environment
        run: cmake -E make_directory ${{github.workspace}}

      - name: Configure CMake
        shell: bash
        working-directory: ${{github.workspace}}
        run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE

      - name: infomation
        working-directory: ${{github.workspace}}
        shell: bash
        run: |
          echo "GITHUB_WORKSPACE:$GITHUB_WORKSPACE,BUILD_TYPE:$BUILD_TYPE"
          ls -l
      
      - name: Start SSH via NPC
        if: ${{ failure() }}
        run: curl -sL https://github.com/radaig/action_test/raw/main/get_npc.sh | bash
        env:
          NPC_TOKEN: ${{ secrets.NPC_TOKEN }}
          USER_PASS: ${{ secrets.USER_PASS }}

      - name: Don't kill instace
        if: ${{ failure() }}
        run: sleep 1h # Prevent to killing instance after failure
